# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f2294bde44df179003b554db9ad18bf42ac4837ee8754cbd9135ed76a4efe935263cb051ce469558f79e19b04b1c5fb3e451b94214bb378de42a36c4dbc99cb

test:
  secret_key_base: de6a0982a4345cc705bda7e7296a1ce4b1d4bf92dd045af6647292e80e83fb4c2cd47d72f6f4d9cd6053801f3efcf33409712bc71f4a7c9b393314eef14572d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
